"""create audit_log table

Revision ID: 0949d00c6416
Revises: 
Create Date: 2026-08-11 15:13:30.059792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0949d00c6416'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Belt-and-suspenders: env.py's do_run_migrations() already creates the
    # schema at runtime before this migration executes, but the migration
    # itself should be self-sufficient/replayable regardless of how it's invoked.
    op.execute('CREATE SCHEMA IF NOT EXISTS "juryai"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gate_blocked', sa.Boolean(), nullable=False),
    sa.Column('gate_regenerated', sa.Boolean(), nullable=False),
    sa.Column('evidence_content_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('streaming', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='juryai'
    )
    op.create_index('ix_audit_log_conversation_id', 'audit_log', ['conversation_id'], unique=False, schema='juryai')
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False, schema='juryai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_created_at', table_name='audit_log', schema='juryai')
    op.drop_index('ix_audit_log_conversation_id', table_name='audit_log', schema='juryai')
    op.drop_table('audit_log', schema='juryai')
    # ### end Alembic commands ###
