from pydantic import BaseModel
from typing import Optional


class ChatRequest(BaseModel):
    question: str
    conversation_id: Optional[str] = None
    use_web_search: bool = False
    web_search_max_results: int = 5


class CitationOut(BaseModel):
    quote: str
    verified: bool
    source: str
    page: int
    content_hash: str = ""


class SourceChunkOut(BaseModel):
    text: str
    source: str
    page: int
    score: float
    verified: bool = False
    domain: str = "internal"  # "internal" (corpus) or "web" — drives frontend source split
    url: Optional[str] = None  # navigable link, only ever set for domain == "web"


# Alias used in SSE source_chunk events
ScoredChunkOut = SourceChunkOut


class WebEvidenceOut(BaseModel):
    title: str
    url: str
    content: str
    score: float
    authority_score: float = 0.0
    source_type: str = "web"
    published_at: str = ""
    retrieved_at: str = ""
    content_hash: str = ""
    citation_id: str = ""


class SupportedClaimOut(BaseModel):
    claim: str
    content_hash: str = ""


class VerificationOut(BaseModel):
    groundedness_score: float = 0.0
    verdict: str = "unsupported"
    supported_claims: list[SupportedClaimOut] = []
    unsupported_claims: list[str] = []
    summary: str = ""
    blocked: bool = False       # gate blocked release (still ungrounded after retry)
    regenerated: bool = False   # answer was regenerated by the gate


class ChatResponse(BaseModel):
    answer: str
    citations: list[CitationOut]
    source_chunks: list[SourceChunkOut] = []
    conversation_id: str
    intent: str
    sources_used: int
    verification: Optional[VerificationOut] = None


class IngestRequest(BaseModel):
    prefix_filter: str = ""
    sync_only: bool = True  # True = incremental (skip already ingested)


class IngestResponse(BaseModel):
    ingested: int
    failed: int
    skipped: int = 0
    total_keys: int
    running: bool = False
    processed: int = 0
    total: int = 0
    current_key: str = ""
    already_running: bool = False


class SyncStatusResponse(BaseModel):
    total_on_s3: int
    ingested: int
    pending: int
    pending_keys: list[str] = []
    running: bool = False
    processed: int = 0
    total: int = 0
    failed: int = 0
    skipped: int = 0
    current_key: str = ""
    started_at: Optional[float] = None
    finished_at: Optional[float] = None
    error: Optional[str] = None
